### ISSUE TITLE
示例代码有缺陷

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [Baidu-AIP/QuickStart#1]
如果图片是非菜品 是没有热量的。
建议main.py的115行进行如下修改
`# 打印图片结果
    for data in result_json["result"]:
        print(u"  菜品名称: " + data["name"])
        has_calorie = data["has_calorie"];
        if(has_calorie):
           print(u"  菜品热量: " + data["calorie"])`

**Comment by meteorasd555** [comment]
已修复
